### ISSUE TITLE
AirplaneLite

### ISSUE THREAD

**Issue by Titaniumtown** [NotMyFault/ServerLib#1]
https://github.com/NotMyFault/ServerLib/blob/f88e5a6cfbbbc108da224ed411bff5f76b50d490/src/main/java/de/notmyfault/serverlib/forks/AirplaneLite.java#L23

This no longer applies as that patch was removed a while ago.

**Comment by NotMyFault** [comment]
Superseded by https://github.com/NotMyFault/ServerLib/issues/2.
